import { useState } from 'react';
import { CheckCircle2, XCircle, RotateCcw, CheckSquare } from 'lucide-react';

const SAMPLE_MCQS = {
  physics: [
    {
      id: 'phy-mcq-1',
      question: 'The electric potential at an equatorial point due to a short electric dipole of dipole moment p at distance r is:',
      options: ['kp / r²', '2kp / r³', 'Zero', '−kp / r²'],
      correct: 2,
      explanation: 'Contributions from +q and −q charges cancel algebraically at any point on the equatorial perpendicular bisector line.'
    },
    {
      id: 'phy-mcq-2',
      question: 'In an AC circuit containing only a pure inductor, the phase angle between alternating voltage and current is:',
      options: ['Current leads voltage by 90°', 'Current lags voltage by 90°', 'In phase with voltage', 'Lags by 180°'],
      correct: 1,
      explanation: 'The back-EMF generated by the inductor causes current to lag voltage by exactly π/2 radians (90°).'
    }
  ],
  chemistry: [
    {
      id: 'chem-mcq-1',
      question: 'Which of the following aqueous solutions exhibits the highest boiling point elevation?',
      options: ['0.1 M Glucose', '0.1 M NaCl', '0.1 M BaCl₂', '0.1 M Al₂(SO₄)₃'],
      correct: 3,
      explanation: 'ΔT_b = i·K_b·m. Al₂(SO₄)₃ dissociates into 2 Al³⁺ + 3 SO₄²⁻ (i = 5), producing the maximum number of particles.'
    },
    {
      id: 'chem-mcq-2',
      question: 'The electronic configuration of a transition metal ion with maximum number of unpaired electrons in 3d series is:',
      options: ['Fe³⁺ (3d⁵)', 'Mn²⁺ (3d⁵)', 'Cr³⁺ (3d³)', 'Both Fe³⁺ and Mn²⁺ (3d⁵)'],
      correct: 3,
      explanation: 'Both Fe³⁺ and Mn²⁺ have 3d⁵ half-filled configuration with 5 unpaired electrons.'
    }
  ],
  biology: [
    {
      id: 'bio-mcq-1',
      question: 'The functional megaspore in an angiosperm typically develops into a female gametophyte that is:',
      options: ['7-celled, 7-nucleate', '8-celled, 8-nucleate', '7-celled, 8-nucleate', '8-celled, 7-nucleate'],
      correct: 2,
      explanation: 'The mature embryo sac has 3 antipodals, 1 central cell with 2 polar nuclei, and egg apparatus (1 egg + 2 synergids) = 7 cells, 8 nuclei.'
    }
  ]
};

export default function McqTabContent({ selectedSubject }) {
  const mcqs = SAMPLE_MCQS[selectedSubject] || SAMPLE_MCQS.physics;
  const [selectedAnswers, setSelectedAnswers] = useState({});

  const handleSelectOption = (questionId, optionIdx) => {
    if (selectedAnswers[questionId] !== undefined) return; // locked once chosen
    setSelectedAnswers(prev => ({ ...prev, [questionId]: optionIdx }));
  };

  const resetQuiz = () => {
    setSelectedAnswers({});
  };

  return (
    <div className="space-y-4 sm:space-y-6 animate-in fade-in duration-300">
      <div className="flex items-center justify-between p-4 sm:p-6 rounded-2xl bg-[var(--bg-elevated)] border border-[var(--border-default)]">
        <div>
          <h3 className="font-serif text-xl sm:text-2xl font-bold text-[var(--text-primary)] flex items-center gap-2">
            <CheckSquare size={20} className="text-[var(--accent-primary)] shrink-0" />
            Board MCQ Quiz Practice
          </h3>
          <p className="font-sans text-xs text-[var(--text-secondary)] mt-1">
            Test conceptual clarity with instant explanation feedback.
          </p>
        </div>
        <button
          onClick={resetQuiz}
          className="inline-flex items-center gap-1.5 px-3 py-1.5 sm:px-3.5 sm:py-2 rounded-xl border border-[var(--border-default)] text-xs font-medium text-[var(--text-secondary)] hover:text-[var(--text-primary)] hover:bg-[var(--bg-surface)] transition-colors cursor-pointer shrink-0"
        >
          <RotateCcw size={13} />
          Reset
        </button>
      </div>

      <div className="space-y-4 sm:space-y-6">
        {mcqs.map((q, idx) => {
          const userChoice = selectedAnswers[q.id];
          const isAnswered = userChoice !== undefined;

          return (
            <div
              key={q.id}
              className="bg-[var(--bg-surface)] border border-[var(--border-default)] rounded-2xl p-4 sm:p-6 shadow-sm space-y-3 sm:space-y-4"
            >
              <div className="flex items-start gap-2.5 sm:gap-3">
                <span className="font-mono text-xs font-bold px-2 py-0.5 sm:py-1 rounded bg-[var(--bg-elevated)] text-[var(--text-secondary)] shrink-0">
                  Q{idx + 1}
                </span>
                <p className="font-serif text-base sm:text-lg font-bold text-[var(--text-primary)] leading-snug">
                  {q.question}
                </p>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-2.5 sm:gap-3 pt-1 sm:pt-2">
                {q.options.map((opt, i) => {
                  let btnStyle = 'bg-[var(--bg-elevated)] border-[var(--border-subtle)] text-[var(--text-primary)] hover:border-[var(--accent-primary)]';

                  if (isAnswered) {
                    if (i === q.correct) {
                      btnStyle = 'bg-green-500/15 border-green-500/60 text-green-700 dark:text-green-300 font-bold';
                    } else if (i === userChoice) {
                      btnStyle = 'bg-red-500/15 border-red-500/60 text-red-700 dark:text-red-300';
                    } else {
                      btnStyle = 'bg-[var(--bg-elevated)]/50 border-[var(--border-subtle)] opacity-50';
                    }
                  }

                  return (
                    <button
                      key={i}
                      disabled={isAnswered}
                      onClick={() => handleSelectOption(q.id, i)}
                      className={`p-3 sm:p-3.5 rounded-xl border text-left text-xs sm:text-sm transition-all flex items-center justify-between gap-2 cursor-pointer ${btnStyle}`}
                    >
                      <span className="break-words">{opt}</span>
                      {isAnswered && i === q.correct && (
                        <CheckCircle2 size={16} className="text-green-600 shrink-0" />
                      )}
                      {isAnswered && i === userChoice && i !== q.correct && (
                        <XCircle size={16} className="text-red-600 shrink-0" />
                      )}
                    </button>
                  );
                })}
              </div>

              {isAnswered && (
                <div className="pt-3 border-t border-[var(--border-subtle)] text-xs text-[var(--text-secondary)] font-sans">
                  <span className="font-bold text-[var(--accent-primary)] mr-1">Explanation:</span>
                  {q.explanation}
                </div>
              )}
            </div>
          );
        })}
      </div>
    </div>
  );
}
